### ISSUE TITLE
won't install on OS X

### ISSUE THREAD

**Issue by theapplepastor** [yoggy/sendosc#3]
Here is where I get an issue

The-MacBook-Pro:oscpack user$ sudo make install
#Mac OS X case
g++ -dynamiclib -Wl,-install_name,liboscpack.so -o liboscpack.so.1.1.0 osc/OscTypes.o osc/OscOutboundPacketStream.o osc/OscReceivedElements.o osc/OscPrintReceivedElements.o ip/posix/UdpSocket.o ip/IpEndpointName.o ip/posix/NetworkingUtils.o -lc
install: /usr/local/lib/liboscpack.so.1.1.0: No such file or directory
make: *** [install] Error 71
The-MacBook-Pro:oscpack user$

**Comment by yoggy** [comment]
Please try running this command...

(1) install homebrew (https://brew.sh/)

    $ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

(2) install cmake

    $ brew install cmake

(3) install oscpack

    $ cd ~
    $ rm -rf oscpack
    $ git clone https://github.com/arturoc/oscpack
    $ make
    $ sudo make install

(4) install sendosc

    $ cd ~
    $ git clone https://github.com/yoggy/sendosc
    $ cd sendosc
    $ cmake .
    $ make 
    $ make install
