### ISSUE TITLE
Q: Does sendosc support sending to multicast address?

### ISSUE THREAD

**Issue by Pilskalns** [yoggy/sendosc#7]
Hi,

Does `sendosc` support sending to multicast address?

I try to run multiple Pedalboard2 instances. With unicast, each Pedalboard2 needs unique port. With multicast multiple instances could listen to the same address:port.

At least, I couldn't get `sendosc` to work with multicast...

**Comment by yoggy** [comment]
sendosc does not support multicast.
The reason is that oscpack does not support multicast.
