### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by XFer012** [yoggy/sendosc#9]
Built sendosc on Linux ARM aarch64 (Ubuntu 18.04.4, Odroid N2).

Tried it with zynaddsubfx on the same machine, port 7777; got this error:

` ./sendosc 127.0.0.1 7777 /part[0,15]/kit[0,15]/padpars/GlobalFilter/basefreq f 1000
sendosc: osc/OscOutboundPacketStream.cpp:166: osc::OutboundPacketStream::OutboundPacketStream(char*, std::size_t): Assertion `sizeof(osc::int32) == 4' failed.
Aborted`

Is there something I could try?
Thanks

**Comment by XFer012** [comment]
The problem lies within liboscpack: it does not manage aarch64 correctly.
Unfortunately it looks like nobody is maintaining it anymore.

**Comment by yoggy** [comment]
Please refer to this patch. https://github.com/yoggy/homebrew-tap/blob/master/oscpack-arm64.patch
